{
 "title": "Demo Day-a",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Kubernetes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Pod Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace=\"default\", deployment=\"demoday-a\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (phase)(kube_pod_status_phase{namespace=\"default\", pod=~\"demoday-a-[a-z0-9]+-[a-z0-9]+\", phase=~\"Running|Pending|Failed\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Replicas(HPA)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_current_replicas{horizontalpodautoscaler=\"demoday-a\", namespace=\"default\"}",
     "legendFormat": "{{horizontalpodautoscaler}}"
    }
   ]
  },
  { "title": "System Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Usages",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{\n    namespace=\"default\",\n    pod=~\"demoday-a-[a-z0-9]+-[a-z0-9]+\", \n    container!=\"POD\",\n    container!=\"\"\n}[1m]))",
     "legendFormat": "demoday-a"
    }
   ]
  },
  {
   "title": "Memory Usages",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"default\", pod=~\"demoday-a-[a-z0-9]+-[a-z0-9]+\", container!=\"POD\", container!=\"\"}) / (1024*1024)",
     "legendFormat": "demoday-a"
    }
   ]
  },
  { "title": "Application Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Domain Status",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"https://demoday-a.dev-k8s.arkain.io/\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=\"https://demoday-a.dev-k8s.arkain.io/\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}